// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdfN-EcDQH2kJP7Qp6uk4skftVHXH2mM',
    appId: '1:37632358817:web:4ab1d96bf93ce258cd73e0',
    messagingSenderId: '37632358817',
    projectId: 'placemate-6cc73',
    authDomain: 'placemate-6cc73.firebaseapp.com',
    storageBucket: 'placemate-6cc73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK2aLE73_sAX5AjHeL8u5sy2lw9OpLzaQ',
    appId: '1:37632358817:android:ed40ed0fc0ae77becd73e0',
    messagingSenderId: '37632358817',
    projectId: 'placemate-6cc73',
    storageBucket: 'placemate-6cc73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFFxajBUsLDw0pxXDfDSTik1kOCf0iVQ',
    appId: '1:37632358817:ios:6474052a71fbc49ccd73e0',
    messagingSenderId: '37632358817',
    projectId: 'placemate-6cc73',
    storageBucket: 'placemate-6cc73.appspot.com',
    iosBundleId: 'com.example.placemate',
  );
}
